#!/bin/bash

#############################################################################################################################

DOTNET_VERSION=""
LANGUAGE_VERSION=""

#############################################################################################################################

GREEN="\e[92m"
RED="\e[91m"
ENDCOLOR="\e[0m"

if [[ -n ${1} && ${1} == "-n" ]] || [[ -n ${1} && ${1} == "--new" ]]
then
    if dotnet new console --framework ${DOTNET_VERSION} --langVersion ${LANGUAGE_VERSION} --use-program-main true --name $2 1> /dev/null
    then
        echo -e 'using System;\nusing System.Runtime.InteropServices;\n\nnamespace '${2}'\n{\n\tinternal unsafe class Program\n\t{\n\t\tstatic void Main(string[] args)\n\t\t{\n\t\t\tConsole.WriteLine("Hello World!");\n\t\t}\n\t}\n}' > './'${2}'/Program.cs'
        echo -e '<Project Sdk="Microsoft.NET.Sdk">\n\n\t<PropertyGroup>\n\t\t<OutputType>Exe</OutputType>\n\t\t<TargetFramework>'${DOTNET_VERSION}'</TargetFramework>\n\t\t<LangVersion>'${LANGUAGE_VERSION}'</LangVersion>\n\t\t<ImplicitUsings>disable</ImplicitUsings>\n\t\t<Nullable>enable</Nullable>\n\t\t<AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n\t</PropertyGroup>\n\n</Project>' > './'${2}'/'${2}'.csproj'
        echo -e "${GREEN}Project creation successful!${ENDCOLOR}"
        exit 0
    else
        echo -e "${RED}Project creation failed!${ENDCOLOR}"
        exit 1
    fi
fi

if [[ -n ${1} && ${1} == "-d" ]] || [[ -n ${1} && ${1} == "--debug" ]]
then
    while true
    do
        read -n 1 -s -r -p $'\rRun: r | Build & Run: b' choice
        echo
        case $choice in
            r)
                ./bin/Debug/net8.0/$(basename $PWD)
                ;;
            b)
                sudo dotnet run
                ;;
            $'\e')
                exit 0
                ;;
        esac
    done
fi

if [[ -n ${1} && ${1} == "--version" ]]
then
    echo -e ".NET version: $(dotnet --version)"
    exit 0
fi

echo -e "\nUsage: ezdot [options]\n\nOptions:\n  -h|--help\tDisplay help.\n  -n|--new\tNew console app.\n  -d|--debug\tDebug console app.\n  --version\tDisplay .NET version.\n"
